spring.application.name=nlc
server.port=${PORT:8080}

spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
spring.datasource.url = ${DB_URL:jdbc:mysql://localhost:3306/thermal}
spring.datasource.username = ${DB_USERNAME:root}
spring.datasource.password = Niresh@1

spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}
